language: generic

deploy:
  provider: s3
  access_key_id:
    secure: "Suu5wlv7HszuU5OLTo3KQ3VZF/PVEGk2PCDdpIveIOHvVxv5z74KowojQH+oMwDDeD2R9+xYQ4AKPG2IbicEGjiBpBr+LwIgJVSka8NJSIy4FXhvzdzlizTwtv0F9G3FUNt36vIC+NUaRQ3CMTeXyO4mHFXyHv2fv9tRJmhGoL+TRc7u3F6we3+5srUok0G2ikKu+3UGLU7MNaeYjcNozH1aH/J5M2pUE7ctGkwWazWshHOpuKOwVIbZ6fRI9ZuJasoNFhqAsE0bdFgPRMFaAv6lVmWB4d/4h9sI5bREHBPddkoA/iSmqBlbqtS3DtdpwnmgvNuMhgo4ZbgP08VEQNGnndOUKW7pqsDzfwjulbjfswmkpxWKk2+Pk3XjmfXZBrrkKUh+OYUNiagvhUlfyeHtgORtAHjRvPuXECUCClpzSpMl71ofNMsR4y3vgGeXaFZv92lQAHqN560FK2Tpcx1WS+QhJm9x6E4IFCseUWwpSWfXIIeEpy8b2+8lIB4LcyixhGIvPoDwJ982g+TgDqudFgSy/9AU7O/1G9+l24Y8eWFdaamzj3vWGe4+uIYSgrDSNh5HdP1f496LnrkbrJ5ZEBL1x695ma5fed8ZSABN3Yu2DyDRK8GOQeFe4c+YmGScQDuhCApSEs+sNsQN/BqPdoycnbWnwZgmNfjwK/M="
  secret_access_key:
    secure: "Vx0lNWBw8eZWzJ4ywkNroBnvjazdNbMKHGBZRHpN6RUpet/XlE1k1A2UumeUbMZ5yxYGHi0uCGtGBQMQ4bU+SVGHbq5G2PQVjUrYog2xEPCrr5GBWqV3TjSJgymgOt+OB2lh9v5rufheCMsiIXMQBk1otS1/nPQLRs9mMSqPhNoyFNCGBtexQWfn4EpOUevYwZUwBhJQHqCtDjOu1GqJj6cZpztjO2TwUOZedUBgN01J8JeZYmkswjh8NAQGrEdMP58ZGdtUGgcqjCXS3bqMIi0uxigxKRNTVtKNjc8xePpNIsgRSrLnZr73kxrbnIntmIqatfMa6VLwtew0sfos5AfYQLTjvZ71oRIYERdLeaA4bcL7uCNERoD5Uqie00v/NrC2VUOi99vAYCD9uI1p3xVcVA840X5EytVPYU4S61jiIORSBLgmnvHsO9Ppjh9TjdZcXDS8Md3aMZTyHCOtGBfxKDS6ezQQxo2Kz2MZmcvqCsOB1sYQR12mm9ujot4+nOBFUHFwtvqpZyAB75r5joiLEXOh2zE3tZ5OW3yati7BYYTjAKFuZ0u3SKP7fGzB1pte7SM1j3uxMXylezWGtpMVoW29yqPNZ2YY4mMkcXzNkegqoTvc591fphioR/asP0Hy/TQuXEQM+8XbBhYMedgJT/y1pyssGZ4qJpfn0EM="
  bucket: andrewmacheret.com
  skip_cleanup: true
  acl: public_read
  region: us-east-1
  default_text_charset: utf-8
  detect_encoding: true
  local_dir: www/
  upload_dir: projects/last-known-mouse-position/
